import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AuthProvider } from '@/context/AuthContext';
import { DataProvider } from '@/context/DataContext';
import MainLayout from '@/components/Layout/MainLayout';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <DataProvider>
            {/* MainLayout으로 감싸서 전역 바텀바와 시트 상태를 유지 */}
            <MainLayout>
              {children}
            </MainLayout>
          </DataProvider>
        </AuthProvider>
      </body>
    </html>
  );
}

